# Generated by Django 3.2.5 on 2021-08-27 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iseeyauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISeeYaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iseeyauser')),
            ],
        ),
    ]
