# Generated by Django 3.2.5 on 2021-08-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_marker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
