# Generated by Django 3.2.5 on 2021-08-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_marker_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile'),
        ),
    ]
