# Generated by Django 3.2.5 on 2021-08-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_marker_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='iseeyamap',
            name='type',
            field=models.CharField(choices=[('address', 'address'), ('profile', 'profile')], default='address', max_length=30),
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.AddField(
            model_name='profilemarker',
            name='iseeyamap',
            field=models.ManyToManyField(to='api.ISeeYaMap'),
        ),
        migrations.AddField(
            model_name='profilemarker',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='profilemarker',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='addressmarker',
            name='iseeyamap',
            field=models.ManyToManyField(to='api.ISeeYaMap'),
        ),
        migrations.AddField(
            model_name='addressmarker',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
