# Generated by Django 3.2.5 on 2021-08-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210828_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('address', 'address'), ('profile', 'profile')], default='address', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilemarker',
            name='iseeyamap',
        ),
        migrations.RemoveField(
            model_name='profilemarker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profilemarker',
            name='profile',
        ),
        migrations.AlterField(
            model_name='iseeyamap',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iseeya_maps', to='api.iseeyauser'),
        ),
        migrations.DeleteModel(
            name='AddressMarker',
        ),
        migrations.DeleteModel(
            name='ProfileMarker',
        ),
        migrations.AddField(
            model_name='marker',
            name='iseeyamap',
            field=models.ManyToManyField(to='api.ISeeYaMap'),
        ),
        migrations.AddField(
            model_name='marker',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='marker',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
