# Generated by Django 3.2.5 on 2021-08-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210828_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='profile',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
