# Generated by Django 3.2.5 on 2021-08-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210828_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
