# Generated by Django 3.2.5 on 2021-08-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_marker_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='iseeyamap',
            field=models.ManyToManyField(related_name='markers', to='api.ISeeYaMap'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile'),
        ),
    ]
