# Generated by Django 3.2.5 on 2021-09-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210828_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iseeyauser',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='iseeya_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.iseeyauser'),
        ),
    ]
