# Generated by Django 3.2.5 on 2021-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='iseeyamap',
        ),
        migrations.AddField(
            model_name='iseeyamap',
            name='markers',
            field=models.ManyToManyField(related_name='iseeya_map', to='api.Marker'),
        ),
    ]
