# Generated by Django 3.2.5 on 2021-09-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210907_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_api_profile_friends_+', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.CreateModel(
            name='ProfileMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_maps', to='api.iseeyauser')),
                ('profiles', models.ManyToManyField(related_name='profile_maps', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locations', models.ManyToManyField(related_name='location_maps', to='api.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_maps', to='api.iseeyauser')),
            ],
        ),
    ]
